WIP WIP WIP REWORD? scripts: Fixed BrokenPipeError in table renderer
Note just the table renderer and related scripts, not in general.

The problem is when you do things like pipe to head -n1, you get this on
python's stderr:

  Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w'
      encoding='utf-8'>
  BrokenPipeError: [Errno 32] Broken pipe

I've seen this warning from time to time, and assumed the fix would be
a simple flag/setting somewhere, but no!

  # from (simplified a bit):
  # https://docs.python.org/3/library/signal.html#note-on-sigpipe
  try:
      ...
      sys.stdout.flush()
  except BrokenPipeError:
      devnull = os.open(os.devnull, os.O_WRONLY)
      os.dup2(devnull, sys.stdout.fileno())

I'm surprised/confused the fix is so complicated for a use case that
seems so common...

---

Rather than applying this to every script, I've just applied it to the
main source of these errors, the table renderer in the csv scripts. (We
do the same thing with KeyboardInterrupt, limit fixes to relevant
scripts atm.)

The purpose of the table renderer _is_ to print a CLI-friendly terminal.
This should probably include conveniences for common bash operations,
head, tail, awk, etc.

---

Also worth noting, an alternative fix is to use awk instead of head:

  awk 'N==1 {print}'

Not a general fix, but may be useful if running into this issue with
other python scripts.