WIP WIP WIP REWORD? rev: Tightened test_exhaustion recycles, loosened elsewhere
This fixes a test bug! Found by test_exhaustion_spam_uzd_fuzz +
LFS3_GBMAP=1 was failing following the recycle logic change:

  tests/test_exhaustion.toml:1469:failure:
          test_exhaustion_spam_uzd_fuzz:
              0084fw1g1o2q1ar14v10g20h21i21j20l2g4m20n2q2o20
  lfs3.c:13140:error: No more free space (lookahead 0/256)
  run 1, 4096x256, 10 ec: 66301 ops
  lifetime: 37438 -> 66301 (x1.77)
  tests/test_exhaustion.toml:2132:assert:
          assert failed with 72931, expected gt 74876
      assert(run_ops[1]*110/100 > 2*run_ops[0]);

I know, I know, this looks an _awfully_ lot like a bug in the new logic,
and not a test bug. But digging into the failure, I think this is just a
result of a slightly more strict interpretation of cfg.block_recycles.

With the previous nlog2(blablabla+1)-1 => mod 2^n-1 counter logic, the
BLOCK_RECYCLES=4 was aligned down to total erases te:

  te = 2^(nlog(2*(4+1)+1)-1)-1
     = 2^(nlog(11)-1)-1
     = 2^3-1
     = 7

Whereas now it is strictly interpreted as:

  te = 2*4+1
     = 9

Some more block_recycles:

  block_recycles  total erases (before)    total erases (after)
  r               2^(nlog(2*(r+1)+1)-1)-1  2*r+1
  0               1                        1
  1               3                        3
  2               3                        5
  3               7                        7
  4               7                        9
  5               7                        11
  6               7                        13
  7               15                       15
  8               15                       17
  10              15                       21
  100             127                      201
  1000            1023                     2001

It's only a difference of 2 compactions/erase, but it's enough to throw
of our wear-leveling check in test_exhaustion_spam_uzd_fuzz (and only
one exhaustion test! two permutations! and only with the gbmap!).

Some of the problem is our exhaustion tests use a very small
ERASE_CYCLES, to minimize an already very long test. Added a comment
that BLOCK_RECYCLES needs to match this.

TLDR: Setting BLOCK_RECYCLES=3 here changes these tests to the same
internal behavior as previously, even if externally it looks quite
different. Note the stricter interpretation gives the user _more_
control, not less.

---

As for relaxing the other BLOCK_RECYCLES, I found this old commit:
76d3c49b.

Turns out both of these using BLOCK_RECYCLES=4 was just a coincidence,
resulting from aligning things to powers-of-two.

Since these have never really found a failure, from what I remember,
and since they already test BLOCK_RECYCLES=1 and 0, I don't see a reason
to not bump these back up. They might run a bit faster.